### ISSUE TITLE
rename base62.ts to base62x.ts

### ISSUE THREAD

**Issue by wadelau** [litert/encodings.js#1]
The script:src/lib/encodings/base62.ts would be better to be renamed to src/lib/encodings/base62x.ts as the original name may lead to misunderstanding as to the actual base62, i.e., 0-61.
In fact this base62.ts is to present code number with 0-63. rt?

**Comment by fenying** [comment]
Oh, u r right. I will fix this later. Thank you.

**Comment by fenying** [comment]
Fixed in `v2.2.0`
